export const LEAD_SOURCE_REQUEST = "LEAD_SOURCE_REQUEST";

export const LEAD_SOURCE_SUCCESS = "LEAD_SOURCE_SUCCESS";

export const LEAD_SOURCE_FAILURE = "LEAD_SOURCE_FAILURE";

export const LEAD_SUB_SOURCE_REQUEST = "LEAD_SUB_SOURCE_REQUEST";

export const LEAD_SUB_SOURCE_SUCCESS = "LEAD_SUB_SOURCE_SUCCESS";

export const LEAD_SUB_SOURCE_FAILURE = "LEAD_SUB_SOURCE_FAILURE";

export const LEAD_CAMPAIGN_REQUEST = "LEAD_CAMPAIGN_REQUEST";

export const LEAD_CAMPAIGN_SUCCESS = "LEAD_CAMPAIGN_SUCCESS";

export const LEAD_CAMPAIGN_FAILURE = "LEAD_CAMPAIGN_FAILURE";

export const LEAD_CAMPAIGN_TERM_REQUEST = "LEAD_CAMPAIGN_TERM_REQUEST";

export const LEAD_CAMPAIGN_TERM_SUCCESS = "LEAD_CAMPAIGN_TERM_SUCCESS";

export const LEAD_CAMPAIGN_TERM_FAILURE = "LEAD_CAMPAIGN_TERM_FAILURE";
export const LEAD_CAMPAIGN_CONTENT_REQUEST = "LEAD_CAMPAIGN_CONTENT_REQUEST";

export const LEAD_CAMPAIGN_CONTENT_SUCCESS = "LEAD_CAMPAIGN_CONTENT_SUCCESS";

export const LEAD_CAMPAIGN_CONTENT_FAILURE = "LEAD_CAMPAIGN_CONTENT_FAILURE";

export const LEAD_FILTER_DATA_REQUEST = "LEAD_FILTER_DATA_REQUEST";

export const LEAD_FILTER_DATA_SUCCESS = "LEAD_FILTER_DATA_SUCCESS";

export const LEAD_FILTER_DATA_FAILURE = "LEAD_FILTER_DATA_FAILURE";

export const LEAD_TABLE_HEAD_REQUEST = "LEAD_TABLE_HEAD_REQUEST";

export const LEAD_TABLE_HEAD_SUCCESS = "LEAD_TABLE_HEAD_SUCCESS";

export const LEAD_TABLE_HEAD_FAILURE = "LEAD_TABLE_HEAD_FAILURE";

export const LEAD_TABLE_DATA_REQUEST = "LEAD_TABLE_DATA_REQUEST";

export const LEAD_TABLE_DATA_SUCCESS = "LEAD_TABLE_DATA_SUCCESS";

export const LEAD_TABLE_DATA_FAILURE = "LEAD_TABLE_DATA_FAILURE";

export const SET_SELECTED_SOURCE_REQUEST = "SET_SELECTED_SOURCE_REQUEST";

export const SET_SELECTED_CHANNEL_SUCCESS = "SET_SELECTED_CHANNEL_SUCCESS";
export const SET_SELECTED_CHANNEL_SUCCESS_ADDLEAD = "SET_SELECTED_CHANNEL_SUCCESS_ADDLEAD";

export const LEAD_STAGE_FAILURE = "LEAD_STAGE_FAILURE";

export const LEAD_STAGE_REQUEST = "LEAD_STAGE_REQUEST";

export const LEAD_STAGE_SUCCESS = "LEAD_STAGE_SUCCESS";

export const LEAD_STATUS_FAILURE = "LEAD_STATUS_FAILURE";

export const LEAD_STATUS_REQUEST = "LEAD_STATUS_REQUEST";

export const LEAD_STATUS_SUCCESS = "LEAD_STATUS_SUCCESS";

export const LEAD_MEDIUM_FAILURE = "LEAD_MEDIUM_FAILURE";

export const LEAD_MEDIUM_REQUEST = "LEAD_MEDIUM_REQUEST";

export const LEAD_MEDIUM_SUCCESS = "LEAD_MEDIUM_SUCCESS";

export const LEAD_CHANNEL_FAILURE = "LEAD_CHANNEL_FAILURE";

export const LEAD_CHANNEL_REQUEST = "LEAD_CHANNEL_REQUEST";

export const LEAD_CHANNEL_SUCCESS = "LEAD_CHANNEL_SUCCESS";

export const LEAD_SUBMIT_FAILURE = "LEAD_SUBMIT_FAILURE";

export const LEAD_SUBMIT_REQUEST = "LEAD_SUBMIT_REQUEST";

export const LEAD_SUBMIT_SUCCESS = "LEAD_SUBMIT_SUCCESS";

export const GET_PROJECT_REQUEST = "GET_PROJECT_REQUEST";

export const GET_PROJECT_FAILURE = "GET_PROJECT_FAILURE";

export const GET_PROJECT_SUCCESS = "GET_PROJECT_SUCCESS";

export const SET_SELECTED_LOCATION = "SET_SELECTED_LOCATION";

export const SET_SELECTED_COUNTRY = "SET_SELECTED_COUNTRY";

export const SET_SELECTED_STATUS = "SET_SELECTED_STATUS";

export const RESET_ADDLEAD_FIELD = "RESET_ADDLEAD_FIELD";

export const SET_SELECTED_SOURCE = "SET_SELECTED_SOURCE";

export const SET_SELECTED_SUBSOURCE = "SET_SELECTED_SUBSOURCE";

export const SET_SELECTED_MEDIUM = "SET_SELECTED_MEDIUM";

export const RESET_SELECTED_STATUS = "RESET_SELECTED_STATUS";

export const SET_SELECTED_CAMPNAME = "SET_SELECTED_CAMPNAME";

export const SET_SELECTED_CAMPTERM = "SET_SELECTED_CAMPTERM";

export const SET_SELECTED_CAMPCONTENT = "SET_SELECTED_CAMPCONTENT";

export const SET_SELECTED_PROJECT = "SET_SELECTED_PROJECT";

export const SET_SELECTED_PRESALE_EXECUTIVE = "SET_SELECTED_PRESALE_EXECUTIVE";

export const SET_SELECTED_SALES_EXECUTIVE = "SET_SELECTED_SALES_EXECUTIVE";

export const SET_FROM_DATE = "SET_FROM_DATE";

export const SET_TO_DATE = "SET_TO_DATE";

export const SET_SEARCH_VALUE = "SET_SEARCH_VALUE";

export const RESET_FILTER = "RESET_FILTER";

export const LEADS_COUNT_REQUEST = "LEADS_COUNT_REQUEST";

export const LEADS_COUNT_FAILURE = "LEADS_COUNT_FAILURE";

export const LEADS_COUNT_SUCCESS = "LEADS_COUNT_FAILURE";

export const SET_DATE_LABEL = "SET_DATE_LABEL";

export const SET_HANDOVER_TRIGGER = "SET_HANDOVER_TRIGGER";

export const SET_ADD_DATA_SUCCESS = "SET_ADD_DATA_SUCCESS";

export const DASHBOSRD_LEADS_COUNT_SUCCESS = "DASHBOSRD_LEADS_COUNT_SUCCESS";
