export const LOAD_LEAD_REQUEST = 'LOAD_LEAD_REQUEST'
export const LOAD_LEAD_SUCCESS = 'LOAD_LEAD_SUCCESS'
export const LOAD_LEAD_FAILURE = 'LOAD_LEAD_FAILURE'


export const SAVE_LEAD_SUCCESS = 'SAVE_LEAD_SUCCESS'
export const EDIT_LEAD_SUCCESS = 'EDIT_LEAD_SUCCESS'

export const SUBMIT_FLAG_TRUE = 'SUBMIT_FLAG_TRUE';
export const SUBMIT_FLAG_FALSE = 'SUBMIT_FLAG_FALSE';

export const LOAD_LEAD_ACTIVITY_REQUEST = 'LOAD_LEAD_ACTIVITY_REQUEST'
export const LOAD_LEAD_ACTIVITY_SUCCESS = 'LOAD_LEAD_ACTIVITY_SUCCESS'
export const LOAD_LEAD_ACTIVITY_FAILURE = 'LOAD_LEAD_ACTIVITY_FAILURE'

export const SAVE_LEAD_DEMOGRAPHICS_SUCCESS = 'SAVE_LEAD_DEMOGRAPHICS_SUCCESS'




 