export const ADD_USER_REQUEST = "ADD_USER_REQUEST";

export const ADD_USER_SUCCESS = "ADD_USER_SUCCESS";

export const ADD_USER_FAILURE = "ADD_USER_FAILURE";

export const GET_USER_REQUEST = "GET_USER_REQUEST";

export const GET_USER_SUCCESS = "GET_USER_SUCCESS";

export const GET_USER_FAILURE = "GET_USER_FAILURE";

export const GET_USER_LIST_REQUEST = "GET_USER_LIST_REQUEST";

export const GET_USER_LIST_SUCCESS = "GET_USER_LIST_SUCCESS";

export const GET_USER_LIST_FAILURE = "GET_USER_LIST_FAILURE";

export const USER_TABLE_HEAD_SUCCESS = "USER_TABLE_HEAD_SUCCESS";

export const USER_TABLE_HEAD_REQUEST = "USER_TABLE_HEAD_REQUEST";

export const USER_TABLE_DATA_SUCCESS = "USER_TABLE_DATA_SUCCESS";

export const USER_TABLE_DATA_REQUEST = "USER_TABLE_DATA_REQUEST";

export const SET_MANAGER_ID = "SET_MANAGER_ID";

export const GET_SALES_REQUEST = "GET_SALES_REQUEST";

export const GET_SALES_FAILURE = "GET_SALES_FAILURE";

export const GET_SALES_SUCCESS = "GET_SALES_SUCCESS";

export const SET_MODAL_FLAG = 'SET_MODAL_FLAG';

export const SET_EDIT_FLAG = 'SET_EDIT_FLAG';
export const SET_EDIT_DATA = 'SET_EDIT_DATA';
export const SET_ERROR_FLAG = 'SET_ERROR_FLAG';

export const SET_FILTER_FLAG_TRUE = 'SET_FILTER_FLAG_TRUE';
export const ADD_USER_SUCCESS_FLAG = 'ADD_USER_SUCCESS_FLAG';

export const SET_RESET_FILTER = 'SET_RESET_FILTER';

